export interface Book {
  id: string
  title: string
  author: string
  price: number
  originalPrice?: number
  category: string
  categorySlug: string
  rating: number
  reviewCount: number
  description: string
  longDescription: string
  coverColors: string[]
  stock: number
  isbn: string
  publisher: string
  year: number
  pages: number
  language: string
  featured?: boolean
  newArrival?: boolean
  bestseller?: boolean
  tags: string[]
}

export interface Category {
  slug: string
  name: string
  description: string
  color: string
  lightColor: string
  count: number
}

export const categories: Category[] = [
  { slug: 'biblias',    name: 'Biblias',              description: 'Todas las traducciones y ediciones', color: '#dc2626', lightColor: '#fee2e2', count: 7 },
  { slug: 'devocionales', name: 'Devocionales',       description: 'Reflexiones diarias para tu fe',    color: '#d97706', lightColor: '#fef3c7', count: 5 },
  { slug: 'teologia',  name: 'Teología',              description: 'Doctrina y estudio profundo',       color: '#4f46e5', lightColor: '#e0e7ff', count: 4 },
  { slug: 'literatura', name: 'Literatura Cristiana', description: 'Novelas, biografías y clásicos',    color: '#059669', lightColor: '#dcfce7', count: 5 },
  { slug: 'crecimiento', name: 'Crecimiento Espiritual', description: 'Transforma tu vida con la Palabra', color: '#0891b2', lightColor: '#e0f2fe', count: 3 },
  { slug: 'familia',   name: 'Familia y Matrimonio',  description: 'Construye un hogar sólido en Cristo', color: '#db2777', lightColor: '#fce7f3', count: 2 },
  { slug: 'apologetica', name: 'Apologética',         description: 'Defiende y comparte tu fe',         color: '#7c3aed', lightColor: '#ede9fe', count: 2 },
  { slug: 'infantil',  name: 'Infantil y Juvenil',    description: 'Fe desde temprana edad',            color: '#ea580c', lightColor: '#ffedd5', count: 2 },
]

const books: Book[] = [
  // ── BIBLIAS ──
  {
    id: 'biblia-rvr60-tapa-dura',
    title: 'Santa Biblia Reina Valera 1960 – Tapa Dura',
    author: 'Sociedad Bíblica',
    price: 24.99,
    originalPrice: 32.00,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.9,
    reviewCount: 3241,
    description: 'La traducción de referencia en el mundo hispanohablante. Texto clásico de la RVR60 en tapa dura con papel biblia de alta calidad.',
    longDescription: 'La Reina Valera 1960 es la versión más leída y respetada en el mundo de habla hispana. Esta edición premium incluye papel biblia de alta calidad, texto a dos columnas, concordancia básica, mapas bíblicos a color y referencias cruzadas. Ideal tanto para estudio personal como para uso en el culto y en la iglesia. Una Biblia que durará toda una vida y es perfecta para regalar en bautismos, bodas y momentos especiales de la fe.',
    coverColors: ['#450a0a', '#991b1b', '#dc2626'],
    stock: 30,
    isbn: '978-0829703542',
    publisher: 'Sociedades Bíblicas Unidas',
    year: 1960,
    pages: 1392,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['biblia', 'RVR60', 'Reina Valera', 'clásica', 'regalo'],
  },
  {
    id: 'biblia-nvi-letra-grande',
    title: 'Santa Biblia NVI – Letra Grande',
    author: 'Biblica',
    price: 19.99,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.8,
    reviewCount: 2156,
    description: 'La Nueva Versión Internacional en letra grande para una lectura cómoda y fluida. Texto moderno y fiel al original hebreo y griego.',
    longDescription: 'La NVI es la traducción más popular en el mundo hispano por su combinación de fidelidad al texto original y lenguaje contemporáneo. Esta edición en letra grande facilita la lectura para todas las edades. Incluye referencias cruzadas, concordancia temática y mapas bíblicos a color. Un regalo perfecto para padres, abuelos y personas que valoran la comodidad de lectura diaria.',
    coverColors: ['#1c1917', '#44403c', '#d4a96a'],
    stock: 25,
    isbn: '978-0829759006',
    publisher: 'Editorial Vida',
    year: 1999,
    pages: 1248,
    language: 'Español',
    bestseller: true,
    tags: ['biblia', 'NVI', 'letra grande', 'moderna'],
  },
  {
    id: 'biblia-estudio-macarthur',
    title: 'Biblia de Estudio MacArthur – NVI',
    author: 'John MacArthur',
    price: 44.99,
    originalPrice: 59.00,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.9,
    reviewCount: 1876,
    description: 'La biblia de estudio definitiva. Más de 20.000 notas exegéticas del Dr. MacArthur que explican el texto versículo a versículo.',
    longDescription: 'Esta Biblia de estudio es considerada por pastores y teólogos como la herramienta más completa disponible en español. Incluye más de 20.000 notas exegéticas del Dr. John MacArthur, introducciones detalladas a cada libro bíblico, artículos temáticos, índice de palabras clave, mapas bíblicos y gráficos ilustrativos. Indispensable para el estudio serio y sistemático de la Palabra de Dios.',
    coverColors: ['#172554', '#1e40af', '#60a5fa'],
    stock: 12,
    isbn: '978-0829762198',
    publisher: 'Editorial Portavoz',
    year: 2004,
    pages: 2016,
    language: 'Español',
    featured: true,
    tags: ['biblia', 'estudio', 'MacArthur', 'exégesis', 'pastor'],
  },
  {
    id: 'biblia-promesas-rvr60',
    title: 'Biblia de Promesas – RVR60',
    author: 'Editorial Unilit',
    price: 22.99,
    originalPrice: 28.00,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.7,
    reviewCount: 1432,
    description: 'Todas las promesas de Dios reunidas y marcadas en el texto. Con índice temático para encontrar la promesa que necesitas.',
    longDescription: 'Identificadas y organizadas sistemáticamente, las miles de promesas que Dios ha hecho a su pueblo están presentadas en esta Biblia especial. Cada promesa está marcada visualmente en el texto con su categoría correspondiente. Incluye un índice completo de promesas clasificadas por tema: sanidad, paz, provisión, perdón, y muchas más. Una herramienta invaluable para el creyente que quiere aferrarse a la Palabra en tiempos difíciles.',
    coverColors: ['#78350f', '#b45309', '#fbbf24'],
    stock: 20,
    isbn: '978-0789918536',
    publisher: 'Editorial Unilit',
    year: 2000,
    pages: 1408,
    language: 'Español',
    bestseller: true,
    tags: ['biblia', 'promesas', 'RVR60', 'estudio'],
  },
  {
    id: 'biblia-familia-nvi',
    title: 'Biblia para la Familia – NVI',
    author: 'Editorial Vida',
    price: 34.99,
    originalPrice: 45.00,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.8,
    reviewCount: 987,
    description: 'La Biblia diseñada para ser leída en familia. Con notas para padres e hijos, preguntas de reflexión y aplicaciones para el hogar.',
    longDescription: 'Esta edición especial está diseñada para fomentar la lectura bíblica familiar. Incluye notas especiales que conectan el texto con situaciones cotidianas, preguntas de reflexión para distintas edades, actividades para hacer en familia y aplicaciones prácticas. La herramienta perfecta para instaurar el tiempo devocional familiar como un hábito sagrado en el hogar cristiano.',
    coverColors: ['#052e16', '#166534', '#4ade80'],
    stock: 15,
    isbn: '978-0829762099',
    publisher: 'Editorial Vida',
    year: 2010,
    pages: 1520,
    language: 'Español',
    featured: true,
    tags: ['biblia', 'familia', 'NVI', 'devocional familiar', 'niños'],
  },
  {
    id: 'biblia-cronologica-nvi',
    title: 'Biblia Cronológica – NVI',
    author: 'Biblica',
    price: 29.99,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.6,
    reviewCount: 654,
    description: 'La Biblia ordenada según el orden cronológico de los eventos. Una perspectiva completamente nueva de la historia bíblica.',
    longDescription: '¿Qué pasaba en el Imperio Romano mientras Jesús predicaba en Galilea? ¿Qué profecías se cumplían durante el exilio en Babilonia? La Biblia Cronológica NVI reordena el texto bíblico según el orden histórico de los eventos, integrando pasajes que se refieren al mismo período. Una experiencia de lectura transformadora que da una nueva perspectiva de la historia de la redención.',
    coverColors: ['#1e1b4b', '#3730a3', '#818cf8'],
    stock: 10,
    isbn: '978-0829762150',
    publisher: 'Editorial Vida',
    year: 2007,
    pages: 1584,
    language: 'Español',
    newArrival: true,
    tags: ['biblia', 'cronológica', 'NVI', 'historia bíblica'],
  },
  {
    id: 'biblia-pescador-nvi',
    title: 'Biblia del Pescador – NVI (Evangelismo)',
    author: 'Tyndale House',
    price: 9.99,
    originalPrice: 14.99,
    category: 'Biblias',
    categorySlug: 'biblias',
    rating: 4.7,
    reviewCount: 823,
    description: 'La Biblia perfecta para evangelismo y para regalar a personas que están comenzando su camino de fe.',
    longDescription: 'Diseñada específicamente para el evangelismo personal y para regalar a personas que están explorando la fe cristiana por primera vez. Su formato compacto, notas explicativas básicas y lenguaje contemporáneo la hacen perfecta para quienes aún no están familiarizados con la Biblia. Incluye guía de primeros pasos en la fe, preguntas frecuentes y plan de lectura para nuevos creyentes.',
    coverColors: ['#042f2e', '#0f766e', '#2dd4bf'],
    stock: 40,
    isbn: '978-1414300207',
    publisher: 'Tyndale House',
    year: 2005,
    pages: 1152,
    language: 'Español',
    newArrival: true,
    tags: ['biblia', 'evangelismo', 'regalo', 'nuevos creyentes', 'NVI'],
  },

  // ── DEVOCIONALES ──
  {
    id: 'jesus-llama',
    title: 'Jesús Llama',
    author: 'Sarah Young',
    price: 14.99,
    originalPrice: 18.99,
    category: 'Devocionales',
    categorySlug: 'devocionales',
    rating: 4.9,
    reviewCount: 5432,
    description: 'El devocional más vendido de la historia moderna. Reflexiones diarias escritas en primera persona desde la perspectiva de Jesús, basadas en la Escritura.',
    longDescription: 'Con más de 30 millones de copias vendidas, "Jesús Llama" ha transformado la vida devocional de millones de creyentes en todo el mundo. Sarah Young escribe reflexiones diarias desde la perspectiva del Señor Jesús, basadas en versículos de la Biblia, invitando al lector a una relación íntima y personal con Cristo. Cada meditación es corta, profunda y práctica para el día a día del creyente.',
    coverColors: ['#78350f', '#b45309', '#fcd34d'],
    stock: 35,
    isbn: '978-1591451884',
    publisher: 'Thomas Nelson',
    year: 2004,
    pages: 400,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['devocional', 'oración', 'Sarah Young', 'reflexión diaria'],
  },
  {
    id: 'en-pos-de-lo-supremo',
    title: 'En Pos de lo Supremo',
    author: 'Oswald Chambers',
    price: 12.99,
    category: 'Devocionales',
    categorySlug: 'devocionales',
    rating: 4.9,
    reviewCount: 2876,
    description: 'Considerado el devocional clásico de la literatura cristiana. Reflexiones profundas para alcanzar la máxima devoción a Dios.',
    longDescription: 'Publicado póstumamente por su esposa, "En Pos de lo Supremo" es posiblemente el devocional más profundo y desafiante jamás escrito. Oswald Chambers llama al creyente a alcanzar la máxima devoción a Dios, sin compromisos ni medias tintas. Sus reflexiones diarias son densas, proféticas y tremendamente relevantes casi un siglo después de haber sido escritas. Un clásico absoluto de la espiritualidad cristiana.',
    coverColors: ['#1e1b4b', '#3730a3', '#a5b4fc'],
    stock: 22,
    isbn: '978-0929239354',
    publisher: 'Discovery House',
    year: 1935,
    pages: 400,
    language: 'Español',
    bestseller: true,
    tags: ['devocional', 'Oswald Chambers', 'clásico', 'devoción'],
  },
  {
    id: 'morning-and-evening-spurgeon',
    title: 'Mañana y Tarde – Spurgeon',
    author: 'Charles H. Spurgeon',
    price: 13.99,
    originalPrice: 17.00,
    category: 'Devocionales',
    categorySlug: 'devocionales',
    rating: 4.8,
    reviewCount: 1654,
    description: 'El devocional clásico del Príncipe de los Predicadores. Dos reflexiones diarias para alimentar tu alma en cualquier momento del día.',
    longDescription: 'Charles Haddon Spurgeon, conocido como el "Príncipe de los Predicadores", compiló este devocional que ofrece dos reflexiones al día: una para la mañana y otra para la tarde. Basadas en versículos específicos de la Biblia, las meditaciones de Spurgeon combinan profundidad teológica con aplicación práctica. Un clásico de la espiritualidad evangélica que sigue siendo profundamente relevante para el cristiano de hoy.',
    coverColors: ['#450a0a', '#7f1d1d', '#dc2626'],
    stock: 18,
    isbn: '978-1619582354',
    publisher: 'Hendrickson Publishers',
    year: 1865,
    pages: 736,
    language: 'Español',
    tags: ['devocional', 'Spurgeon', 'clásico', 'predicación'],
  },
  {
    id: 'devocional-hombres-tony-evans',
    title: 'Devocional para Hombres',
    author: 'Tony Evans',
    price: 13.99,
    category: 'Devocionales',
    categorySlug: 'devocionales',
    rating: 4.7,
    reviewCount: 876,
    description: '52 semanas de reflexiones bíblicas diseñadas específicamente para el hombre de hoy: fe, liderazgo y carácter cristiano.',
    longDescription: 'El Dr. Tony Evans, uno de los líderes evangélicos más respetados, escribió este devocional dirigido específicamente a los hombres. Durante 52 semanas, aborda temas cruciales como el liderazgo familiar, la integridad en el trabajo, la gestión de las emociones, la vida de oración y el discipulado. Un recurso práctico y desafiante para el hombre que quiere crecer en su fe y en su rol como esposo, padre y líder.',
    coverColors: ['#0c2340', '#1e3a5f', '#38bdf8'],
    stock: 16,
    isbn: '978-0802412942',
    publisher: 'Moody Publishers',
    year: 2018,
    pages: 384,
    language: 'Español',
    newArrival: true,
    tags: ['devocional', 'hombres', 'liderazgo', 'Tony Evans'],
  },
  {
    id: 'susurros-esperanza-beth-moore',
    title: 'Susurros de Esperanza',
    author: 'Beth Moore',
    price: 12.99,
    category: 'Devocionales',
    categorySlug: 'devocionales',
    rating: 4.7,
    reviewCount: 987,
    description: 'Un devocional de 10 semanas que lleva al lector a una experiencia íntima con Dios a través de la oración y la Palabra.',
    longDescription: 'Beth Moore, reconocida maestra bíblica, diseñó este devocional de 10 semanas para ayudar a los creyentes a desarrollar una vida de oración más profunda. Cada día incluye un versículo de reflexión, una meditación sobre la oración, espacios para escribir peticiones personales y un tiempo de escucha ante Dios. Un recurso especialmente valioso para momentos de incertidumbre, renovación espiritual o búsqueda de dirección.',
    coverColors: ['#4c0519', '#881337', '#f43f5e'],
    stock: 14,
    isbn: '978-0805442670',
    publisher: 'B&H Español',
    year: 2012,
    pages: 224,
    language: 'Español',
    newArrival: true,
    tags: ['devocional', 'oración', 'Beth Moore', 'mujeres', 'esperanza'],
  },

  // ── TEOLOGÍA ──
  {
    id: 'institucion-religion-cristiana-calvino',
    title: 'Institución de la Religión Cristiana',
    author: 'Juan Calvino',
    price: 34.99,
    originalPrice: 45.00,
    category: 'Teología',
    categorySlug: 'teologia',
    rating: 4.8,
    reviewCount: 543,
    description: 'La obra teológica más influyente de la Reforma Protestante. El sistema doctrinal completo de la fe cristiana reformada.',
    longDescription: 'Publicada en 1536 y revisada sucesivamente, la "Institución" de Juan Calvino es la exposición sistemática más completa e influyente de la teología reformada. Organizada en cuatro libros que cubren el conocimiento de Dios, la fe en Cristo, la gracia y la Iglesia, esta obra continúa siendo estudiada en seminarios de todo el mundo. Una lectura formativa para todo cristiano que quiera entender los fundamentos de su fe.',
    coverColors: ['#1e1b4b', '#3730a3', '#6366f1'],
    stock: 8,
    isbn: '978-8489938144',
    publisher: 'Felire',
    year: 1536,
    pages: 1344,
    language: 'Español',
    tags: ['teología', 'Calvino', 'Reforma', 'doctrina', 'reformada'],
  },
  {
    id: 'confesiones-san-agustin',
    title: 'Confesiones',
    author: 'San Agustín de Hipona',
    price: 11.99,
    category: 'Teología',
    categorySlug: 'teologia',
    rating: 4.8,
    reviewCount: 1234,
    description: 'La autobiografía espiritual más influyente de la historia. El viaje de Agustín desde el pecado hasta el encuentro transformador con Dios.',
    longDescription: 'Escritas en el siglo IV d.C., las "Confesiones" son el relato íntimo y apasionado de la conversión de Agustín de Hipona. Con una prosa extraordinaria, narra cómo buscó la felicidad en el placer, el éxito y la filosofía hasta encontrar el verdadero descanso en Dios. "Nos hiciste para ti, Señor, y nuestro corazón está inquieto hasta que descanse en ti." Una lectura que sigue conmoviendo después de 1.600 años.',
    coverColors: ['#3b1f0f', '#7c3500', '#d97706'],
    stock: 15,
    isbn: '978-8432141485',
    publisher: 'Rialp',
    year: 400,
    pages: 384,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['teología', 'Agustín', 'patrística', 'conversión', 'clásico'],
  },
  {
    id: 'precio-del-discipulado-bonhoeffer',
    title: 'El Precio del Discipulado',
    author: 'Dietrich Bonhoeffer',
    price: 13.99,
    category: 'Teología',
    categorySlug: 'teologia',
    rating: 4.9,
    reviewCount: 1543,
    description: 'El libro que expone el costo real de seguir a Jesús. Un desafío radical contra la "gracia barata" que debilita a la Iglesia.',
    longDescription: 'Escrito en la Alemania nazi de 1937, este libro del mártir Dietrich Bonhoeffer es uno de los más importantes del siglo XX. Bonhoeffer denuncia la "gracia barata" —el perdón sin arrepentimiento, la fe sin obediencia— y llama a la Iglesia a abrazar el discipulado costoso que demanda Jesús. Un libro que desafía la complacencia religiosa y convoca a una fe auténtica, dispuesta incluso a morir por sus convicciones.',
    coverColors: ['#0f172a', '#1e293b', '#64748b'],
    stock: 20,
    isbn: '978-0684815008',
    publisher: 'Sígueme',
    year: 1937,
    pages: 304,
    language: 'Español',
    bestseller: true,
    tags: ['teología', 'Bonhoeffer', 'discipulado', 'gracia', 'mártir'],
  },
  {
    id: 'progreso-del-peregrino-bunyan',
    title: 'El Progreso del Peregrino',
    author: 'John Bunyan',
    price: 10.99,
    category: 'Teología',
    categorySlug: 'teologia',
    rating: 4.8,
    reviewCount: 1876,
    description: 'La alegoría cristiana más leída de todos los tiempos. El viaje de Cristiano desde la Ciudad de la Destrucción hasta la Ciudad Celestial.',
    longDescription: 'Escrita por John Bunyan mientras estaba en prisión por predicar el evangelio, "El Progreso del Peregrino" es la alegoría cristiana más publicada de la historia después de la Biblia. El viaje de Cristiano a través del Pantano de la Desesperación, el Castillo de la Duda, la Feria de las Vanidades y la Montaña de la Dificultad sigue siendo una representación perfecta del camino de fe cristiana, lleno de profundas verdades espirituales.',
    coverColors: ['#1c1917', '#44403c', '#a8a29e'],
    stock: 18,
    isbn: '978-8476459553',
    publisher: 'Clie',
    year: 1678,
    pages: 336,
    language: 'Español',
    tags: ['teología', 'alegoría', 'Bunyan', 'clásico', 'peregrino'],
  },

  // ── LITERATURA CRISTIANA ──
  {
    id: 'mero-cristianismo-lewis',
    title: 'Mero Cristianismo',
    author: 'C.S. Lewis',
    price: 12.99,
    category: 'Literatura Cristiana',
    categorySlug: 'literatura',
    rating: 4.9,
    reviewCount: 4231,
    description: 'La defensa intelectual más brillante de la fe cristiana del siglo XX. Lewis lleva al escéptico desde la ley moral hasta la persona de Cristo.',
    longDescription: 'Originalmente transmitido como charlas radiofónicas en la BBC durante la Segunda Guerra Mundial, "Mero Cristianismo" es la obra más influyente de C.S. Lewis. A través de argumentos lógicos y accesibles, Lewis presenta una defensa del cristianismo que parte de la ley moral inherente a todos los seres humanos y llega a la persona de Jesucristo. Millones de personas han encontrado o renovado su fe a través de este libro extraordinario.',
    coverColors: ['#052e16', '#166534', '#22c55e'],
    stock: 28,
    isbn: '978-0060652920',
    publisher: 'Rayo (HarperCollins)',
    year: 1952,
    pages: 288,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['apologética', 'C.S. Lewis', 'filosofía', 'fe', 'evangelio'],
  },
  {
    id: 'cronicas-de-narnia-lewis',
    title: 'Las Crónicas de Narnia',
    author: 'C.S. Lewis',
    price: 16.99,
    originalPrice: 22.00,
    category: 'Literatura Cristiana',
    categorySlug: 'literatura',
    rating: 4.9,
    reviewCount: 3456,
    description: 'La saga de fantasía más querida de la literatura cristiana. Siete libros que revelan las verdades del evangelio a través de la maravillosa historia de Narnia.',
    longDescription: 'C.S. Lewis creó el mundo de Narnia como una "suposición": ¿cómo sería si Cristo viniera a un mundo de animales parlantes? Los siete libros de las Crónicas de Narnia presentan el evangelio completo a través de la historia de Aslan, el Gran León. Leídas con igual gozo por niños y adultos, estas novelas son una puerta de entrada a las verdades más profundas del cristianismo, contadas a través de aventuras fascinantes.',
    coverColors: ['#042f2e', '#0f766e', '#14b8a6'],
    stock: 22,
    isbn: '978-8467575385',
    publisher: 'Destino',
    year: 1956,
    pages: 768,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['fantasía', 'C.S. Lewis', 'Narnia', 'familia', 'alegoría'],
  },
  {
    id: 'en-sus-manos-corrie-ten-boom',
    title: 'En Sus Manos',
    author: 'Corrie ten Boom',
    price: 12.99,
    category: 'Literatura Cristiana',
    categorySlug: 'literatura',
    rating: 4.9,
    reviewCount: 2876,
    description: 'El testimonio extraordinario de una mujer que sobrevivió a los campos de concentración nazis con su fe en Cristo intacta. Un libro que transforma vidas.',
    longDescription: 'Corrie ten Boom y su familia escondían judíos en su casa de Haarlem durante la ocupación nazi. Cuando fueron descubiertos, los enviaron a los peores campos de concentración. Este libro narra cómo su fe en Cristo no solo sobrevivió al horror del Holocausto, sino que se profundizó hasta convertirse en el fundamento inquebrantable de su vida. "No hay foso tan profundo que el amor de Dios no sea más profundo aún." Una de las historias más conmovedoras de la historia cristiana.',
    coverColors: ['#1a0030', '#3b0763', '#7c3aed'],
    stock: 20,
    isbn: '978-0800794699',
    publisher: 'Chosen Books',
    year: 1971,
    pages: 256,
    language: 'Español',
    bestseller: true,
    tags: ['testimonio', 'holocausto', 'fe', 'Corrie ten Boom', 'historia'],
  },
  {
    id: 'la-cabana-william-paul-young',
    title: 'La Cabaña',
    author: 'William Paul Young',
    price: 13.99,
    category: 'Literatura Cristiana',
    categorySlug: 'literatura',
    rating: 4.6,
    reviewCount: 1987,
    description: 'Una novela que lleva a millones a replantearse su imagen de Dios. Un encuentro inesperado con la Trinidad en lo más oscuro del dolor.',
    longDescription: 'Tras la tragedia que destroza su familia, Mack Phillips recibe una invitación misteriosa a una cabaña abandonada en las montañas. Lo que encuentra allí cambiará para siempre su comprensión de Dios, el dolor y el perdón. Con más de 20 millones de copias vendidas, "La Cabaña" ha acompañado a millones de personas en sus momentos de mayor oscuridad y ha renovado la fe de quienes estaban a punto de rendirse.',
    coverColors: ['#172554', '#1e3a5f', '#93c5fd'],
    stock: 18,
    isbn: '978-8415189183',
    publisher: 'Obelisco',
    year: 2007,
    pages: 288,
    language: 'Español',
    newArrival: true,
    tags: ['novela', 'Trinidad', 'dolor', 'perdón', 'fe'],
  },
  {
    id: 'bonhoeffer-metaxas',
    title: 'Bonhoeffer: Pastor, Mártir, Profeta',
    author: 'Eric Metaxas',
    price: 18.99,
    originalPrice: 25.00,
    category: 'Literatura Cristiana',
    categorySlug: 'literatura',
    rating: 4.8,
    reviewCount: 1123,
    description: 'La biografía definitiva de Dietrich Bonhoeffer. Un teólogo alemán que se enfrentó a Hitler y pagó el precio supremo con su vida.',
    longDescription: 'Eric Metaxas narra la extraordinaria vida de Dietrich Bonhoeffer: teólogo brillante, pastor comprometido, agente de la resistencia alemana contra el nazismo y mártir cristiano. Con acceso a documentos inéditos y escritos personales, Metaxas traza el desarrollo espiritual e intelectual de un hombre cuya coherencia entre fe y acción sigue desafiando e inspirando a creyentes de todo el mundo. Una lectura obligada para todo cristiano que quiera entender lo que cuesta la fe verdadera.',
    coverColors: ['#0c0a09', '#1c1917', '#78716c'],
    stock: 12,
    isbn: '978-1595552464',
    publisher: 'Thomas Nelson',
    year: 2010,
    pages: 608,
    language: 'Español',
    tags: ['biografía', 'Bonhoeffer', 'Segunda Guerra Mundial', 'mártir'],
  },

  // ── CRECIMIENTO ESPIRITUAL ──
  {
    id: 'una-vida-con-proposito',
    title: 'Una Vida con Propósito',
    author: 'Rick Warren',
    price: 14.99,
    category: 'Crecimiento Espiritual',
    categorySlug: 'crecimiento',
    rating: 4.8,
    reviewCount: 8765,
    description: 'El libro cristiano más vendido de la historia moderna. Responde la pregunta más importante de la existencia: ¿Para qué estoy aquí?',
    longDescription: 'Rick Warren responde la pregunta más fundamental de la existencia humana: ¿para qué fui creado? Basado en más de 1.200 versículos bíblicos, presenta cinco propósitos que Dios tiene para cada vida: adoración, compañerismo, discipulado, ministerio y evangelismo. Más de 50 millones de copias vendidas en 85 idiomas lo convierten en uno de los libros más influyentes de todos los tiempos.',
    coverColors: ['#052e16', '#15803d', '#86efac'],
    stock: 30,
    isbn: '978-0829731590',
    publisher: 'Editorial Vida',
    year: 2002,
    pages: 336,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['crecimiento', 'propósito', 'Rick Warren', 'vida cristiana'],
  },
  {
    id: 'gracia-max-lucado',
    title: 'Gracia: Más que lo Imaginamos',
    author: 'Max Lucado',
    price: 12.99,
    category: 'Crecimiento Espiritual',
    categorySlug: 'crecimiento',
    rating: 4.7,
    reviewCount: 1876,
    description: 'La obra más profunda de Max Lucado sobre el regalo más grande: la gracia de Dios que transforma el corazón humano.',
    longDescription: 'Max Lucado, uno de los escritores cristianos más queridos del mundo, explora en este libro el concepto central del evangelio: la gracia. No como un concepto teológico abstracto, sino como una fuerza viva que transforma pecadores en santos, esclavos en hijos y el corazón más endurecido en una vasija de amor. Una lectura que devuelve la emoción y el asombro ante el regalo inmerecido del evangelio de Cristo.',
    coverColors: ['#78350f', '#b45309', '#fbbf24'],
    stock: 22,
    isbn: '978-0718014520',
    publisher: 'Grupo Nelson',
    year: 2012,
    pages: 224,
    language: 'Español',
    newArrival: true,
    tags: ['gracia', 'Max Lucado', 'evangelio', 'crecimiento espiritual'],
  },
  {
    id: 'dios-nunca-se-da-por-vencido',
    title: 'Dios Nunca se Da por Vencido Contigo',
    author: 'Max Lucado',
    price: 11.99,
    category: 'Crecimiento Espiritual',
    categorySlug: 'crecimiento',
    rating: 4.6,
    reviewCount: 1234,
    description: 'A través de la historia de Jacob, Lucado muestra cómo Dios persiste en su amor incluso cuando nosotros fallamos.',
    longDescription: 'A través de la historia de Jacob —mentiroso, estafador y fugitivo—, Max Lucado muestra cómo Dios nunca abandona a quienes ama, incluso cuando hacen todo lo posible para merecer su rechazo. Una meditación profunda sobre la gracia tenaz de Dios que persigue, transforma y redime. Especialmente valioso para quienes sienten que han ido demasiado lejos para ser perdonados o para quienes atraviesan una crisis de fe.',
    coverColors: ['#064e3b', '#0f766e', '#34d399'],
    stock: 16,
    isbn: '978-1400202966',
    publisher: 'Thomas Nelson',
    year: 2020,
    pages: 224,
    language: 'Español',
    newArrival: true,
    tags: ['Max Lucado', 'gracia', 'Jacob', 'perseverancia', 'fe'],
  },

  // ── FAMILIA Y MATRIMONIO ──
  {
    id: 'los-5-lenguajes-del-amor',
    title: 'Los 5 Lenguajes del Amor',
    author: 'Gary Chapman',
    price: 13.99,
    originalPrice: 17.99,
    category: 'Familia y Matrimonio',
    categorySlug: 'familia',
    rating: 4.8,
    reviewCount: 9876,
    description: 'El libro que ha transformado millones de matrimonios. Descubre cómo hablar el idioma del amor de tu cónyuge de manera eficaz.',
    longDescription: 'Gary Chapman revolucionó la forma en que entendemos el amor en las relaciones al identificar los cinco lenguajes del amor: palabras de afirmación, actos de servicio, regalos, tiempo de calidad y contacto físico. Cuando aprendes el lenguaje de amor de tu cónyuge, tu matrimonio se transforma. Con más de 20 millones de copias vendidas y basado en principios bíblicos, es el recurso de consejería matrimonial más recomendado en iglesias de todo el mundo.',
    coverColors: ['#4c0519', '#9f1239', '#fb7185'],
    stock: 28,
    isbn: '978-0789918338',
    publisher: 'Editorial Unilit',
    year: 1992,
    pages: 224,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['matrimonio', 'amor', 'Gary Chapman', 'familia', 'relaciones'],
  },
  {
    id: 'el-matrimonio-que-siempre-quisiste',
    title: 'El Matrimonio que Siempre Quisiste',
    author: 'Gary Chapman',
    price: 12.99,
    category: 'Familia y Matrimonio',
    categorySlug: 'familia',
    rating: 4.7,
    reviewCount: 1543,
    description: 'Gary Chapman ofrece principios bíblicos prácticos para construir el matrimonio que Dios diseñó desde el principio.',
    longDescription: 'Basado en décadas de consejería matrimonial cristiana, Gary Chapman presenta los principios bíblicos que marcan la diferencia entre un matrimonio que sobrevive y uno que prospera. Aborda la comunicación, el manejo del conflicto, las expectativas, las finanzas y la vida espiritual de la pareja desde una perspectiva firmemente basada en la Escritura. Un libro que puede iniciar una nueva y hermosa etapa en tu relación.',
    coverColors: ['#500724', '#9d174d', '#f472b6'],
    stock: 20,
    isbn: '978-0829752694',
    publisher: 'Editorial Portavoz',
    year: 2005,
    pages: 224,
    language: 'Español',
    newArrival: true,
    tags: ['matrimonio', 'Gary Chapman', 'familia cristiana', 'pareja'],
  },

  // ── APOLOGÉTICA ──
  {
    id: 'el-caso-de-cristo-strobel',
    title: 'El Caso de Cristo',
    author: 'Lee Strobel',
    price: 13.99,
    category: 'Apologética',
    categorySlug: 'apologetica',
    rating: 4.8,
    reviewCount: 3456,
    description: 'Un periodista ateo investiga con rigor la resurrección de Jesucristo. Sus conclusiones sorprendentes lo cambiaron todo.',
    longDescription: 'Lee Strobel era periodista del Chicago Tribune y un ateo convencido cuando su esposa se convirtió al cristianismo. Decidido a demostrar que la fe cristiana era intelectualmente insostenible, entrevistó a los mejores expertos en historia, arqueología, medicina forense y filosofía. Lo que encontró lo llevó a la conclusión de que la resurrección de Jesús es el evento más bien documentado de la historia antigua. Este libro sigue siendo uno de los recursos apologéticos más efectivos disponibles.',
    coverColors: ['#172554', '#1e40af', '#93c5fd'],
    stock: 24,
    isbn: '978-0829762891',
    publisher: 'Editorial Vida',
    year: 1998,
    pages: 352,
    language: 'Español',
    featured: true,
    bestseller: true,
    newArrival: true,
    tags: ['apologética', 'resurrección', 'Lee Strobel', 'evidencia', 'periodismo'],
  },
  {
    id: 'dios-no-esta-muerto',
    title: 'Dios No Está Muerto',
    author: 'Rice Broocks',
    price: 12.99,
    category: 'Apologética',
    categorySlug: 'apologetica',
    rating: 4.6,
    reviewCount: 1234,
    description: 'Una respuesta intelectualmente rigurosa al ateísmo moderno. Evidencias filosóficas, científicas e históricas de la existencia de Dios.',
    longDescription: 'En respuesta al nuevo ateísmo de Dawkins, Hitchens y Harris, Rice Broocks presenta evidencias filosóficas, científicas e históricas de la existencia de Dios y la verdad del evangelio. Escrito con rigor intelectual pero accesible para todo lector, este libro equipa a los creyentes para defender su fe con argumentos sólidos y responde honestamente las objeciones más frecuentes al cristianismo en el mundo contemporáneo.',
    coverColors: ['#1a1a2e', '#16213e', '#0f3460'],
    stock: 18,
    isbn: '978-0718026622',
    publisher: 'Grupo Nelson',
    year: 2013,
    pages: 256,
    language: 'Español',
    tags: ['apologética', 'ateísmo', 'evidencia', 'Dios', 'filosofía'],
  },

  // ── INFANTIL Y JUVENIL ──
  {
    id: 'mi-primera-biblia-ilustrada',
    title: 'Mi Primera Biblia Ilustrada',
    author: 'Varios Autores',
    price: 12.99,
    category: 'Infantil y Juvenil',
    categorySlug: 'infantil',
    rating: 4.9,
    reviewCount: 3456,
    description: 'Las grandes historias de la Biblia narradas y adaptadas para los más pequeños. Con ilustraciones vibrantes y lenguaje accesible.',
    longDescription: 'Esta hermosa Biblia para niños presenta más de 80 historias bíblicas del Antiguo y Nuevo Testamento adaptadas para niños de 3 a 8 años. Las ilustraciones a todo color son expresivas y atractivas, y el texto ha sido simplificado sin perder la esencia del mensaje bíblico. Incluye una oración al final de cada historia para que padres e hijos puedan orar juntos. El regalo perfecto para bautismos, cumpleaños y primeras comuniones.',
    coverColors: ['#7c2d12', '#c2410c', '#fb923c'],
    stock: 35,
    isbn: '978-0829736595',
    publisher: 'Editorial Vida',
    year: 2008,
    pages: 256,
    language: 'Español',
    bestseller: true,
    tags: ['infantil', 'Biblia', 'niños', 'ilustrada', 'regalo'],
  },
  {
    id: 'jesus-storybook-bible',
    title: 'Jesús Storybook Bible',
    author: 'Sally Lloyd-Jones',
    price: 14.99,
    originalPrice: 18.99,
    category: 'Infantil y Juvenil',
    categorySlug: 'infantil',
    rating: 4.9,
    reviewCount: 4321,
    description: 'La Biblia infantil más aclamada del mundo. Cada historia susurra el nombre de Jesús. Un tesoro para toda la familia.',
    longDescription: 'Sally Lloyd-Jones escribió esta Biblia con la convicción de que "cada historia de la Biblia susurra el nombre de Jesús". Con un texto poético y profundo, y las magníficas ilustraciones de Jago, esta Biblia narra las grandes historias de la Escritura mostrando cómo todas apuntan a la salvación en Jesús. Leída con igual emoción por niños y adultos, es considerada una obra maestra de la literatura cristiana infantil y un regalo que cambia vidas.',
    coverColors: ['#3b0764', '#7e22ce', '#c084fc'],
    stock: 30,
    isbn: '978-0310715252',
    publisher: 'Zonderkidz',
    year: 2007,
    pages: 352,
    language: 'Español',
    featured: true,
    bestseller: true,
    newArrival: true,
    tags: ['infantil', 'Biblia', 'Sally Lloyd-Jones', 'Jesús', 'familia'],
  },
]

export default books

export function getAllBooks(): Book[] {
  return books
}

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id)
}

export function getFeaturedBooks(): Book[] {
  return books.filter((book) => book.featured)
}

export function getBestsellers(): Book[] {
  return books.filter((book) => book.bestseller)
}

export function getNewArrivals(): Book[] {
  return books.filter((book) => book.newArrival)
}

export function getBooksByCategory(slug: string): Book[] {
  return books.filter((book) => book.categorySlug === slug)
}

export function getRelatedBooks(book: Book, count = 4): Book[] {
  return books.filter((b) => b.categorySlug === book.categorySlug && b.id !== book.id).slice(0, count)
}

export function searchBooks(query: string): Book[] {
  const q = query.toLowerCase()
  return books.filter(
    (book) =>
      book.title.toLowerCase().includes(q) ||
      book.author.toLowerCase().includes(q) ||
      book.tags.some((tag) => tag.toLowerCase().includes(q)) ||
      book.category.toLowerCase().includes(q)
  )
}
