export interface Book {
  id: string
  title: string
  author: string
  price: number
  originalPrice?: number
  category: string
  categorySlug: string
  rating: number
  reviewCount: number
  description: string
  longDescription: string
  coverColors: string[]
  stock: number
  isbn: string
  publisher: string
  year: number
  pages: number
  language: string
  featured?: boolean
  newArrival?: boolean
  bestseller?: boolean
  tags: string[]
}

export interface Category {
  slug: string
  name: string
  description: string
  color: string
  lightColor: string
  count: number
}

export const categories: Category[] = [
  { slug: 'literatura', name: 'Literatura', description: 'Novelas, cuentos y poesía', color: '#7c3aed', lightColor: '#ede9fe', count: 8 },
  { slug: 'ciencia', name: 'Ciencia y Tecnología', description: 'Descubre el universo', color: '#0891b2', lightColor: '#e0f2fe', count: 5 },
  { slug: 'historia', name: 'Historia', description: 'El pasado que nos define', color: '#d97706', lightColor: '#fef3c7', count: 4 },
  { slug: 'negocios', name: 'Negocios', description: 'Finanzas y emprendimiento', color: '#059669', lightColor: '#dcfce7', count: 4 },
  { slug: 'filosofia', name: 'Filosofía', description: 'El arte de pensar', color: '#4f46e5', lightColor: '#e0e7ff', count: 3 },
  { slug: 'arte', name: 'Arte y Diseño', description: 'Creatividad sin límites', color: '#db2777', lightColor: '#fce7f3', count: 3 },
  { slug: 'infantil', name: 'Infantil', description: 'Para los más pequeños', color: '#ef4444', lightColor: '#fee2e2', count: 2 },
  { slug: 'autoayuda', name: 'Autoayuda', description: 'Crece y mejora cada día', color: '#10b981', lightColor: '#d1fae5', count: 3 },
]

const books: Book[] = [
  // LITERATURA
  {
    id: 'cien-anos-soledad',
    title: 'Cien Años de Soledad',
    author: 'Gabriel García Márquez',
    price: 18.99,
    originalPrice: 24.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.9,
    reviewCount: 2847,
    description: 'La obra cumbre del realismo mágico. La saga de los Buendía en el mítico Macondo es un viaje épico a través del amor, la soledad y el tiempo.',
    longDescription: 'Publicada en 1967, Cien Años de Soledad narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo. Obra clave para que García Márquez ganara el Premio Nobel de Literatura en 1982. Un universo donde lo cotidiano y lo fantástico se entrelazan con una prosa incomparable. Esta edición incluye prólogo del autor y notas históricas.',
    coverColors: ['#4c1d95', '#7c3aed', '#a78bfa'],
    stock: 15,
    isbn: '978-8497592208',
    publisher: 'Cátedra',
    year: 1967,
    pages: 471,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['clásico', 'realismo mágico', 'Colombia', 'Nobel'],
  },
  {
    id: '1984',
    title: '1984',
    author: 'George Orwell',
    price: 12.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.8,
    reviewCount: 3241,
    description: 'La distopía más influyente del siglo XX. Un mundo donde el Gran Hermano lo vigila todo y la verdad es lo que el Partido decide.',
    longDescription: 'En el año 1984, el mundo está dividido en tres superpotencias totalitarias. Winston Smith trabaja en el Ministerio de la Verdad reescribiendo la historia. Su historia de amor y rebelión secreta contra el sistema es una de las advertencias más poderosas jamás escritas sobre el totalitarismo, la vigilancia masiva y la manipulación del lenguaje.',
    coverColors: ['#1e3a5f', '#1d4ed8', '#60a5fa'],
    stock: 22,
    isbn: '978-8445000335',
    publisher: 'Destino',
    year: 1949,
    pages: 368,
    language: 'Español',
    bestseller: true,
    tags: ['distopía', 'clásico', 'política', 'ciencia ficción'],
  },
  {
    id: 'la-sombra-del-viento',
    title: 'La Sombra del Viento',
    author: 'Carlos Ruiz Zafón',
    price: 16.99,
    originalPrice: 21.00,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.8,
    reviewCount: 1894,
    description: 'Un niño encuentra un libro misterioso en el Cementerio de los Libros Olvidados. Una historia de amor, secretos y la Barcelona de posguerra.',
    longDescription: 'En la Barcelona de la posguerra, Daniel Sempere descubre un libro que cambiará su vida para siempre. A medida que investiga el paradero de su autor, descubre una historia de amor trágico, secretos oscuros y una conspiración que amenaza con destruirlo todo. Una novela emocionante que rinde homenaje al poder de los libros y la literatura.',
    coverColors: ['#1c1917', '#44403c', '#d4a96a'],
    stock: 18,
    isbn: '978-8408163367',
    publisher: 'Planeta',
    year: 2001,
    pages: 560,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['misterio', 'Barcelona', 'España', 'histórico'],
  },
  {
    id: 'el-alquimista',
    title: 'El Alquimista',
    author: 'Paulo Coelho',
    price: 13.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.6,
    reviewCount: 4523,
    description: 'La fábula más vendida de la historia moderna. Un pastor español emprende un viaje hacia sus sueños y descubre el secreto del universo.',
    longDescription: 'Santiago, un joven pastor andaluz, sueña repetidamente con un tesoro escondido junto a las Pirámides de Egipto. Guiado por presagios y el alquimista más sabio del mundo, emprende un viaje de autodescubrimiento que le enseña que "cuando quieres algo, todo el universo conspira para que realices tu deseo". Traducida a 88 idiomas, es una de las novelas más leídas del planeta.',
    coverColors: ['#78350f', '#b45309', '#fbbf24'],
    stock: 30,
    isbn: '978-8408052944',
    publisher: 'Planeta',
    year: 1988,
    pages: 208,
    language: 'Español',
    tags: ['espiritual', 'aventura', 'autoayuda', 'fábula'],
  },
  {
    id: 'don-quijote',
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    price: 14.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.7,
    reviewCount: 1234,
    description: 'La obra más importante de la literatura en lengua española. Las aventuras del Caballero de la Triste Figura son eternas.',
    longDescription: 'Considerada la primera novela moderna de la literatura universal, Don Quijote de la Mancha narra las aventuras de Alonso Quijano, quien enloquecido por la lectura de novelas de caballerías decide convertirse en caballero andante. Junto a su escudero Sancho Panza, emprende hazañas en busca de justicia y honor. Una obra que transcendió su época para convertirse en símbolo imperecedero de la humanidad.',
    coverColors: ['#7f1d1d', '#991b1b', '#f87171'],
    stock: 12,
    isbn: '978-8467033939',
    publisher: 'Alfaguara',
    year: 1605,
    pages: 1056,
    language: 'Español',
    bestseller: true,
    tags: ['clásico español', 'caballería', 'siglo XVII'],
  },
  {
    id: 'los-pilares-de-la-tierra',
    title: 'Los Pilares de la Tierra',
    author: 'Ken Follett',
    price: 19.99,
    originalPrice: 26.00,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.8,
    reviewCount: 2678,
    description: 'La épica saga medieval de la construcción de una catedral. Amor, poder y fe en la Inglaterra del siglo XII.',
    longDescription: 'Ambientada en la Inglaterra del siglo XII, esta magistral novela histórica narra la construcción de una catedral gótica en el ficticio pueblo de Kingsbridge. A través de décadas de guerras, amores, traiciones e intrigas de la Iglesia, los destinos de prior Philip, la constructora Ellen, el maestro constructor Tom y el villano William Hamleigh se entrelazan en una trama apasionante.',
    coverColors: ['#1e1b4b', '#312e81', '#818cf8'],
    stock: 9,
    isbn: '978-8401352836',
    publisher: 'Plaza & Janés',
    year: 1989,
    pages: 1008,
    language: 'Español',
    featured: true,
    tags: ['histórico', 'medieval', 'saga', 'catedral'],
  },
  {
    id: 'crimen-y-castigo',
    title: 'Crimen y Castigo',
    author: 'Fiódor Dostoyevski',
    price: 13.99,
    originalPrice: 17.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.7,
    reviewCount: 1876,
    description: 'El gran estudio psicológico del crimen y la culpa. Raskólnikov comete el crimen perfecto... pero ¿puede vivir con ello?',
    longDescription: 'Rodión Raskólnikov, un estudiante pobre en San Petersburgo, comete un asesinato creyendo que los fines justifican los medios. Lo que sigue es un devastador análisis psicológico de la culpa, la redención y la naturaleza humana. Una de las obras más profundas de la literatura universal, que sigue siendo tremendamente actual en su exploración del relativismo moral.',
    coverColors: ['#3b0764', '#6b21a8', '#c084fc'],
    stock: 14,
    isbn: '978-8420674940',
    publisher: 'Alianza Editorial',
    year: 1866,
    pages: 672,
    language: 'Español',
    tags: ['literatura rusa', 'clásico', 'psicológico', 'crimen'],
  },
  {
    id: 'el-gran-gatsby',
    title: 'El Gran Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 11.99,
    category: 'Literatura',
    categorySlug: 'literatura',
    rating: 4.5,
    reviewCount: 2156,
    description: 'La novela definitiva sobre el sueño americano. Jay Gatsby, las fiestas más lujosas y un amor que no puede ser.',
    longDescription: 'Nueva York, los locos años 20. Jay Gatsby da las fiestas más fastuosas del Long Island Sound, pero todo su esplendor apunta hacia un solo objetivo: recuperar a Daisy Buchanan, el amor perdido de su juventud. A través de los ojos del narrador Nick Carraway, Fitzgerald disecciona con brillantez la superficialidad, el exceso y la corrupción del sueño americano.',
    coverColors: ['#064e3b', '#065f46', '#34d399'],
    stock: 20,
    isbn: '978-8492977420',
    publisher: 'Anagrama',
    year: 1925,
    pages: 224,
    language: 'Español',
    tags: ['clásico americano', 'años 20', 'sueño americano'],
  },

  // CIENCIA Y TECNOLOGÍA
  {
    id: 'sapiens',
    title: 'Sapiens: De Animales a Dioses',
    author: 'Yuval Noah Harari',
    price: 17.99,
    category: 'Ciencia y Tecnología',
    categorySlug: 'ciencia',
    rating: 4.7,
    reviewCount: 5234,
    description: 'Un fascinante viaje por la historia de la humanidad. ¿Cómo llegamos a dominar el planeta? ¿Qué nos hace tan especiales?',
    longDescription: 'En este superventas global, Harari traza la historia de la especie humana desde las sabanas africanas hasta los imperios del siglo XXI. Explica cómo la Revolución Cognitiva, la Revolución Agrícola y la Revolución Científica transformaron a un primate sin importancia en el amo del mundo. Un libro que cambiará para siempre tu forma de entender la historia y el futuro.',
    coverColors: ['#0c4a6e', '#0369a1', '#38bdf8'],
    stock: 25,
    isbn: '978-8499926223',
    publisher: 'Debate',
    year: 2011,
    pages: 496,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['historia', 'humanidad', 'ciencia', 'evolución'],
  },
  {
    id: 'una-breve-historia-del-tiempo',
    title: 'Una Breve Historia del Tiempo',
    author: 'Stephen Hawking',
    price: 14.99,
    category: 'Ciencia y Tecnología',
    categorySlug: 'ciencia',
    rating: 4.6,
    reviewCount: 2341,
    description: 'El libro de física más vendido de la historia. Hawking hace accesible el origen del universo, los agujeros negros y el tiempo.',
    longDescription: 'Desde el Big Bang hasta los agujeros negros, Stephen Hawking lleva al lector a un extraordinario viaje a través del espacio y el tiempo. Escrito para el público general, este libro revolucionario explica los conceptos más complejos de la física moderna de forma accesible y apasionante. Con más de 10 millones de copias vendidas, es uno de los libros de ciencia más influyentes de todos los tiempos.',
    coverColors: ['#0f172a', '#1e3a5f', '#3b82f6'],
    stock: 18,
    isbn: '978-8498921861',
    publisher: 'Crítica',
    year: 1988,
    pages: 272,
    language: 'Español',
    tags: ['física', 'cosmología', 'divulgación', 'universo'],
  },
  {
    id: 'homo-deus',
    title: 'Homo Deus: Breve Historia del Mañana',
    author: 'Yuval Noah Harari',
    price: 17.99,
    category: 'Ciencia y Tecnología',
    categorySlug: 'ciencia',
    rating: 4.5,
    reviewCount: 2134,
    description: '¿Qué le depara el futuro a la humanidad? La continuación de Sapiens explora el mundo del siglo XXI y más allá.',
    longDescription: 'Tras examinar nuestro pasado en Sapiens, Harari vuelve su mirada hacia el futuro. ¿Cuál será el próximo gran proyecto de la humanidad? ¿Podemos vencer a la muerte, alcanzar la felicidad divina y adquirir poderes de dioses? Este libro perspicaz y provocador explora los proyectos, los sueños y las pesadillas que moldearán el siglo XXI.',
    coverColors: ['#0c0a09', '#292524', '#78716c'],
    stock: 16,
    isbn: '978-8499926711',
    publisher: 'Debate',
    year: 2015,
    pages: 480,
    language: 'Español',
    newArrival: true,
    tags: ['historia', 'futuro', 'humanidad', 'tecnología'],
  },
  {
    id: 'la-fisica-del-futuro',
    title: 'La Física del Futuro',
    author: 'Michio Kaku',
    price: 15.99,
    originalPrice: 19.99,
    category: 'Ciencia y Tecnología',
    categorySlug: 'ciencia',
    rating: 4.4,
    reviewCount: 756,
    description: 'Computadoras del tamaño de células, coches voladores y teletransportación. Los científicos más brillantes revelan el siglo XXII.',
    longDescription: 'El célebre físico Michio Kaku entrevistó a los científicos más punteros del mundo para pintar el cuadro más completo jamás trazado de las próximas décadas. Con la mirada puesta en el año 2100, Kaku examina el futuro de los ordenadores, la inteligencia artificial, la medicina, los viajes espaciales y el dinero. Un libro fascinante que muestra cómo la ciencia actual transformará nuestras vidas.',
    coverColors: ['#172554', '#1e40af', '#93c5fd'],
    stock: 11,
    isbn: '978-8499920641',
    publisher: 'Debate',
    year: 2011,
    pages: 480,
    language: 'Español',
    newArrival: true,
    tags: ['física', 'futuro', 'tecnología', 'ciencia ficción'],
  },
  {
    id: 'el-universo-elegante',
    title: 'El Universo Elegante',
    author: 'Brian Greene',
    price: 16.99,
    category: 'Ciencia y Tecnología',
    categorySlug: 'ciencia',
    rating: 4.5,
    reviewCount: 987,
    description: 'La mejor introducción a la teoría de cuerdas. Greene explica de forma brillante cómo podría ser la teoría del todo.',
    longDescription: 'La teoría de cuerdas propone que el universo está compuesto por diminutas cuerdas vibrantes de energía. Brian Greene, uno de sus principales investigadores, explica de forma extraordinariamente accesible esta revolucionaria teoría que podría unificar toda la física. Ganador del Premio Pulitzer, este libro es una obra maestra de la divulgación científica.',
    coverColors: ['#042f2e', '#134e4a', '#14b8a6'],
    stock: 8,
    isbn: '978-8484326960',
    publisher: 'Crítica',
    year: 1999,
    pages: 448,
    language: 'Español',
    tags: ['física', 'teoría de cuerdas', 'divulgación', 'cosmología'],
  },

  // HISTORIA
  {
    id: 'armas-germenes-y-acero',
    title: 'Armas, Gérmenes y Acero',
    author: 'Jared Diamond',
    price: 16.99,
    category: 'Historia',
    categorySlug: 'historia',
    rating: 4.6,
    reviewCount: 1543,
    description: '¿Por qué algunas civilizaciones conquistaron a otras? La respuesta no está en la raza sino en la geografía.',
    longDescription: 'Premio Pulitzer 1998. Diamond argumenta de forma brillante que el dominio de Occidente no se debe a ninguna superioridad racial o intelectual, sino a accidentes geográficos y ecológicos. La disponibilidad de plantas cultivables, animales domesticables y el eje este-oeste de Eurasia fueron las verdaderas armas que determinaron el destino de las civilizaciones.',
    coverColors: ['#3f2b10', '#92400e', '#d97706'],
    stock: 14,
    isbn: '978-8483069349',
    publisher: 'Debate',
    year: 1997,
    pages: 608,
    language: 'Español',
    bestseller: true,
    tags: ['historia', 'antropología', 'civilización', 'Pulitzer'],
  },
  {
    id: 'el-nombre-de-la-rosa',
    title: 'El Nombre de la Rosa',
    author: 'Umberto Eco',
    price: 15.99,
    category: 'Historia',
    categorySlug: 'historia',
    rating: 4.7,
    reviewCount: 1234,
    description: 'Un monje medievalista investiga una serie de misteriosas muertes en una abadía italiana. Una obra maestra intelectual.',
    longDescription: 'Italia, 1327. El monje franciscano Guillermo de Baskerville y su novicio Adso de Melk llegan a una abadía benedictina para participar en un debate teológico. Pero una serie de muertes misteriosas los convierte en investigadores. Eco teje una trama de suspense intelectual que combina filosofía medieval, semiótica y novela policíaca en una obra sin precedentes.',
    coverColors: ['#1a0505', '#450a0a', '#991b1b'],
    stock: 11,
    isbn: '978-8432217241',
    publisher: 'Lumen',
    year: 1980,
    pages: 560,
    language: 'Español',
    tags: ['histórico', 'misterio', 'medieval', 'Italia'],
  },
  {
    id: 'la-historia-interminable',
    title: 'La Historia Interminable',
    author: 'Michael Ende',
    price: 14.99,
    category: 'Historia',
    categorySlug: 'historia',
    rating: 4.8,
    reviewCount: 2341,
    description: 'Bastian abre un libro y se adentra en el mundo de Fantasía. Una novela que celebra el poder mágico de la imaginación y la lectura.',
    longDescription: 'Bastian Baltasar Bux es un niño solitario que encuentra un libro misterioso en una librería de segunda mano. Mientras lo lee, descubre que el mundo de Fantasía, un reino de seres imaginarios, está siendo devorado por una nada misteriosa. Solo él puede salvar Fantasía, pero para hacerlo deberá cruzar la frontera entre la realidad y la ficción. Un clásico de la literatura fantástica.',
    coverColors: ['#042f2e', '#065f46', '#10b981'],
    stock: 17,
    isbn: '978-8420432472',
    publisher: 'Alfaguara',
    year: 1979,
    pages: 512,
    language: 'Español',
    tags: ['fantasía', 'juvenil', 'clásico', 'imaginación'],
  },
  {
    id: 'historia-del-arte',
    title: 'Historia del Arte',
    author: 'E.H. Gombrich',
    price: 32.99,
    originalPrice: 42.00,
    category: 'Historia',
    categorySlug: 'historia',
    rating: 4.8,
    reviewCount: 892,
    description: 'El libro de historia del arte más vendido de todos los tiempos. Desde las cuevas prehistóricas hasta el arte contemporáneo.',
    longDescription: 'Desde las pinturas rupestres de las cavernas hasta el arte experimental del siglo XX, Gombrich narra de manera magistral y apasionante la historia del arte occidental. Con centenares de ilustraciones a color, este libro es al mismo tiempo un texto de referencia para estudiantes y una obra indispensable para todo aquel que quiera disfrutar del arte. Traducida a 30 idiomas y con más de 6 millones de ejemplares vendidos.',
    coverColors: ['#451a03', '#7c2d12', '#ea580c'],
    stock: 6,
    isbn: '978-8446004714',
    publisher: 'Alianza',
    year: 1950,
    pages: 688,
    language: 'Español',
    featured: true,
    tags: ['arte', 'historia', 'ilustrado', 'referencia'],
  },

  // NEGOCIOS
  {
    id: 'padre-rico-padre-pobre',
    title: 'Padre Rico, Padre Pobre',
    author: 'Robert T. Kiyosaki',
    price: 15.99,
    category: 'Negocios',
    categorySlug: 'negocios',
    rating: 4.6,
    reviewCount: 6234,
    description: 'El libro de finanzas personales más vendido de la historia. Aprende a hacer que el dinero trabaje para ti.',
    longDescription: 'Robert Kiyosaki desafía el pensamiento convencional sobre el dinero y la riqueza. A través de las lecciones de sus dos "padres" — el suyo propio y el de su amigo —, explica por qué los ricos se hacen más ricos, por qué la clase media lucha y por qué los pobres se quedan pobres. Un libro que ha cambiado la vida financiera de millones de personas en todo el mundo.',
    coverColors: ['#064e3b', '#15803d', '#86efac'],
    stock: 28,
    isbn: '978-8466329545',
    publisher: 'Debolsillo',
    year: 1997,
    pages: 352,
    language: 'Español',
    bestseller: true,
    tags: ['finanzas', 'inversión', 'riqueza', 'educación financiera'],
  },
  {
    id: 'habitos-atomicos',
    title: 'Hábitos Atómicos',
    author: 'James Clear',
    price: 16.99,
    originalPrice: 21.90,
    category: 'Negocios',
    categorySlug: 'negocios',
    rating: 4.8,
    reviewCount: 8923,
    description: 'La guía definitiva para construir buenos hábitos y eliminar los malos. Pequeños cambios, resultados extraordinarios.',
    longDescription: 'James Clear, uno de los expertos en hábitos más respetados del mundo, revela estrategias prácticas que te enseñarán exactamente cómo formar buenos hábitos, romper los malos y dominar los pequeños comportamientos que conducen a resultados extraordinarios. Si tienes dificultades para cambiar tus hábitos, el problema no eres tú. El problema es tu sistema.',
    coverColors: ['#052e16', '#166534', '#22c55e'],
    stock: 35,
    isbn: '978-8418075544',
    publisher: 'Paidós',
    year: 2018,
    pages: 336,
    language: 'Español',
    featured: true,
    bestseller: true,
    newArrival: true,
    tags: ['hábitos', 'productividad', 'psicología', 'cambio'],
  },
  {
    id: 'el-arte-de-empezar',
    title: 'El Arte de Empezar 2.0',
    author: 'Guy Kawasaki',
    price: 16.99,
    category: 'Negocios',
    categorySlug: 'negocios',
    rating: 4.4,
    reviewCount: 876,
    description: 'La guía definitiva para emprendedores. Desde el gurú de Silicon Valley que lanzó el Macintosh.',
    longDescription: 'Actualizado para la era digital, este libro es el manual imprescindible para cualquier persona que quiera crear algo significativo. Kawasaki comparte los secretos que aprendió trabajando en Apple y como inversor de startups exitosas. Desde cómo crear una startup hasta cómo hacer crecer una empresa consolidada, esta guía práctica cubre todo lo que necesitas saber.',
    coverColors: ['#0c2340', '#1e3a5f', '#3b82f6'],
    stock: 13,
    isbn: '978-8441537019',
    publisher: 'Anaya',
    year: 2015,
    pages: 352,
    language: 'Español',
    newArrival: true,
    tags: ['emprendimiento', 'startups', 'Silicon Valley', 'negocios'],
  },
  {
    id: 'los-7-habitos',
    title: 'Los 7 Hábitos de la Gente Altamente Efectiva',
    author: 'Stephen R. Covey',
    price: 15.99,
    category: 'Negocios',
    categorySlug: 'negocios',
    rating: 4.7,
    reviewCount: 7234,
    description: 'El clásico del liderazgo personal y profesional. Los principios atemporales que transforman vidas.',
    longDescription: 'Este libro es el referente del desarrollo personal y profesional desde hace más de tres décadas. Covey presenta un enfoque holístico e integrado para resolver problemas personales y profesionales. Los siete hábitos son principios universales que, aplicados correctamente, crean eficacia duradera. Con más de 25 millones de copias vendidas en 40 idiomas, es uno de los libros más influyentes del siglo XX.',
    coverColors: ['#1c1917', '#292524', '#78716c'],
    stock: 22,
    isbn: '978-8408143369',
    publisher: 'Paidós',
    year: 1989,
    pages: 432,
    language: 'Español',
    bestseller: true,
    tags: ['liderazgo', 'productividad', 'autoayuda', 'efectividad'],
  },

  // FILOSOFÍA
  {
    id: 'el-mundo-de-sofia',
    title: 'El Mundo de Sofía',
    author: 'Jostein Gaarder',
    price: 14.99,
    category: 'Filosofía',
    categorySlug: 'filosofia',
    rating: 4.7,
    reviewCount: 3421,
    description: 'Una novela filosófica extraordinaria. La joven Sofía recibe cartas misteriosas que la llevan a través de toda la historia de la filosofía.',
    longDescription: 'Un día, Sofía Amundsen encuentra en su buzón una nota anónima con la pregunta: "¿Quién eres?" Así comienza un extraordinario viaje filosófico a través de la historia del pensamiento occidental, desde los presocráticos hasta Sartre. Esta novela es a la vez un thriller filosófico y el curso de filosofía más leído del mundo. Traducida a más de 60 idiomas.',
    coverColors: ['#1e1b4b', '#3730a3', '#818cf8'],
    stock: 19,
    isbn: '978-8466326285',
    publisher: 'Siruela',
    year: 1991,
    pages: 640,
    language: 'Español',
    bestseller: true,
    tags: ['filosofía', 'novela', 'educación', 'historia del pensamiento'],
  },
  {
    id: 'la-republica',
    title: 'La República',
    author: 'Platón',
    price: 11.99,
    category: 'Filosofía',
    categorySlug: 'filosofia',
    rating: 4.5,
    reviewCount: 876,
    description: 'El diálogo filosófico más influyente de la historia. Platón define la justicia, el Estado ideal y el conocimiento.',
    longDescription: 'En este magistral diálogo socrático, Platón aborda las preguntas más fundamentales sobre la justicia, el conocimiento, el alma y la organización política ideal. A través de Sócrates y sus interlocutores, construye su visión del Estado perfecto, presenta el famoso mito de la caverna y sienta las bases de la filosofía política occidental. Una lectura indispensable para entender el pensamiento occidental.',
    coverColors: ['#3b1f0f', '#7c3500', '#d97706'],
    stock: 16,
    isbn: '978-8420649054',
    publisher: 'Alianza',
    year: -380,
    pages: 560,
    language: 'Español',
    tags: ['filosofía', 'Platón', 'política', 'clásico griego'],
  },
  {
    id: 'el-arte-de-vivir',
    title: 'El Arte de Vivir',
    author: 'Epicteto',
    price: 12.99,
    category: 'Filosofía',
    categorySlug: 'filosofia',
    rating: 4.6,
    reviewCount: 654,
    description: 'La sabiduría estoica aplicada a la vida cotidiana. Principios de Epicteto para alcanzar la serenidad y la libertad interior.',
    longDescription: 'Este manual del filósofo estoico Epicteto es una guía práctica para vivir con sabiduría, resiliencia y ecuanimidad. Sus principios, escritos hace dos mil años, son sorprendentemente modernos y aplicables a los desafíos actuales. El estoicismo, la filosofía de Marco Aurelio, Séneca y Epicteto, vive un renacimiento en nuestra era por su enfoque práctico de la felicidad y la virtud.',
    coverColors: ['#1a1a2e', '#16213e', '#0f3460'],
    stock: 20,
    isbn: '978-8415601982',
    publisher: 'Edaf',
    year: 125,
    pages: 192,
    language: 'Español',
    newArrival: true,
    tags: ['estoicismo', 'filosofía práctica', 'sabiduría', 'felicidad'],
  },

  // ARTE Y DISEÑO
  {
    id: 'robar-como-un-artista',
    title: 'Roba como un Artista',
    author: 'Austin Kleon',
    price: 13.99,
    category: 'Arte y Diseño',
    categorySlug: 'arte',
    rating: 4.7,
    reviewCount: 1234,
    description: 'Las 10 cosas que nadie te enseña sobre creatividad. Un libro breve, visual e inspirador para todo creativo.',
    longDescription: 'Austin Kleon comparte los secretos de la creatividad que aprendió como escritor y artista. Con un lenguaje directo y lleno de humor, explica cómo todos los artistas, músicos, escritores y diseñadores "roban" de sus referentes para crear algo nuevo y personal. Un libro visualmente estimulante que te liberará de la parálisis creativa y te inspirará a crear sin miedo.',
    coverColors: ['#1a0030', '#3b0763', '#7c3aed'],
    stock: 24,
    isbn: '978-8493990800',
    publisher: 'Aguilar',
    year: 2012,
    pages: 160,
    language: 'Español',
    newArrival: true,
    tags: ['creatividad', 'arte', 'diseño', 'inspiración'],
  },
  {
    id: 'frida-kahlo-obra-completa',
    title: 'Frida Kahlo: Obra Completa',
    author: 'Helga Prignitz-Poda',
    price: 34.99,
    originalPrice: 45.00,
    category: 'Arte y Diseño',
    categorySlug: 'arte',
    rating: 4.9,
    reviewCount: 456,
    description: 'La edición más completa sobre la vida y obra de Frida Kahlo. Más de 150 pinturas a todo color con textos analíticos.',
    longDescription: 'Una edición de lujo que recoge la obra completa de Frida Kahlo, con más de 150 pinturas reproducidas en alta resolución. Incluye ensayos sobre su vida, contexto histórico y análisis detallado de cada obra. Un volumen imprescindible para todo amante del arte y la cultura mexicana, con textos en español y English.',
    coverColors: ['#7c2d12', '#c2410c', '#fb923c'],
    stock: 5,
    isbn: '978-3836572682',
    publisher: 'Taschen',
    year: 2020,
    pages: 336,
    language: 'Español/English',
    featured: true,
    tags: ['arte', 'México', 'libro de arte', 'surrealismo'],
  },
  {
    id: 'the-design-of-everyday-things',
    title: 'El Diseño de las Cosas Cotidianas',
    author: 'Don Norman',
    price: 18.99,
    category: 'Arte y Diseño',
    categorySlug: 'arte',
    rating: 4.6,
    reviewCount: 892,
    description: 'La biblia del diseño centrado en el usuario. Por qué algunos objetos nos frustran y otros nos hacen la vida más fácil.',
    longDescription: 'Don Norman analiza por qué algunos objetos cotidianos son difíciles de usar y otros resultan intuitivos. Con ejemplos fascinantes —desde puertas que nadie sabe si empujar o tirar hasta termostatos incomprensibles—, establece los principios fundamentales del buen diseño. Este libro, leído por millones de diseñadores, ingenieros y psicólogos, ha transformado la forma en que pensamos sobre los objetos.',
    coverColors: ['#500724', '#9d174d', '#f472b6'],
    stock: 10,
    isbn: '978-8418714986',
    publisher: 'Reverté',
    year: 1988,
    pages: 368,
    language: 'Español',
    tags: ['diseño', 'UX', 'psicología', 'usabilidad'],
  },

  // AUTOAYUDA
  {
    id: 'la-inteligencia-emocional',
    title: 'La Inteligencia Emocional',
    author: 'Daniel Goleman',
    price: 14.99,
    category: 'Autoayuda',
    categorySlug: 'autoayuda',
    rating: 4.6,
    reviewCount: 5432,
    description: 'El bestseller que revolucionó la psicología. Por qué el coeficiente intelectual no lo es todo para triunfar en la vida.',
    longDescription: 'Daniel Goleman argumenta que el cociente intelectual no es el factor determinante del éxito personal y profesional. Las habilidades emocionales —autoconciencia, autocontrol, empatía y habilidades sociales— son las que marcan la diferencia. Con investigaciones pioneras y casos reales, Goleman demuestra que la inteligencia emocional puede aprenderse y mejorarse a cualquier edad.',
    coverColors: ['#0c4a6e', '#075985', '#38bdf8'],
    stock: 26,
    isbn: '978-8472453937',
    publisher: 'Kairós',
    year: 1995,
    pages: 496,
    language: 'Español',
    bestseller: true,
    tags: ['psicología', 'emociones', 'autoayuda', 'liderazgo'],
  },
  {
    id: 'el-poder-del-ahora',
    title: 'El Poder del Ahora',
    author: 'Eckhart Tolle',
    price: 14.99,
    category: 'Autoayuda',
    categorySlug: 'autoayuda',
    rating: 4.5,
    reviewCount: 4123,
    description: 'Una guía para la iluminación espiritual. Aprende a vivir en el momento presente y liberarte del sufrimiento innecesario.',
    longDescription: 'Eckhart Tolle es considerado uno de los maestros espirituales más influyentes del mundo. En este libro, explica cómo la mayor parte de nuestro sufrimiento proviene de identificarnos con nuestros pensamientos y vivir en el pasado o el futuro en lugar del presente. Una guía práctica y transformadora para encontrar la paz interior en el momento presente.',
    coverColors: ['#14532d', '#166534', '#4ade80'],
    stock: 21,
    isbn: '978-8497599498',
    publisher: 'Grijalbo',
    year: 1997,
    pages: 224,
    language: 'Español',
    tags: ['espiritualidad', 'mindfulness', 'presencia', 'paz interior'],
  },

  // INFANTIL
  {
    id: 'el-principito',
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    price: 9.99,
    category: 'Infantil',
    categorySlug: 'infantil',
    rating: 4.9,
    reviewCount: 8765,
    description: 'El libro más leído y traducido del mundo. Un poema sobre la infancia, la soledad y el amor que nos transforma para siempre.',
    longDescription: 'Un piloto que aterriza de emergencia en el desierto del Sahara conoce a un extraño niño, el principito, que viene de un asteroide lejano. A través de sus aventuras en distintos planetas, el principito aprende sobre el amor, la amistad y la naturaleza humana. Con más de 300 millones de copias vendidas y traducido a 505 idiomas, es el libro más leído de la humanidad.',
    coverColors: ['#7c2d12', '#b91c1c', '#f87171'],
    stock: 40,
    isbn: '978-8478887194',
    publisher: 'Salamandra',
    year: 1943,
    pages: 112,
    language: 'Español',
    featured: true,
    bestseller: true,
    tags: ['infantil', 'clásico', 'poético', 'amor', 'amistad'],
  },
  {
    id: 'harry-potter-piedra',
    title: 'Harry Potter y la Piedra Filosofal',
    author: 'J.K. Rowling',
    price: 14.99,
    originalPrice: 18.99,
    category: 'Infantil',
    categorySlug: 'infantil',
    rating: 4.9,
    reviewCount: 15432,
    description: 'El primer libro de la saga más vendida de la historia. Comienza la magia en Hogwarts.',
    longDescription: 'Harry Potter es un niño huérfano que vive con sus despreciables tíos hasta que, en su undécimo cumpleaños, descubre que es un mago y que hay todo un mundo mágico esperándole. En Hogwarts, la escuela de magia y hechicería, Harry hará amigos para toda la vida, aprenderá a hacer magia y descubrirá la verdad sobre sus padres y sobre el oscuro mago que quiso matarle. El comienzo de una serie que ha encantado a generaciones.',
    coverColors: ['#3b0764', '#7e22ce', '#c084fc'],
    stock: 33,
    isbn: '978-8498386318',
    publisher: 'Salamandra',
    year: 1997,
    pages: 272,
    language: 'Español',
    bestseller: true,
    tags: ['infantil', 'magia', 'fantasía', 'juvenil', 'saga'],
  },
]

export default books

export function getAllBooks(): Book[] {
  return books
}

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id)
}

export function getFeaturedBooks(): Book[] {
  return books.filter((book) => book.featured)
}

export function getBestsellers(): Book[] {
  return books.filter((book) => book.bestseller)
}

export function getNewArrivals(): Book[] {
  return books.filter((book) => book.newArrival)
}

export function getBooksByCategory(slug: string): Book[] {
  return books.filter((book) => book.categorySlug === slug)
}

export function getRelatedBooks(book: Book, count = 4): Book[] {
  return books.filter((b) => b.categorySlug === book.categorySlug && b.id !== book.id).slice(0, count)
}

export function searchBooks(query: string): Book[] {
  const q = query.toLowerCase()
  return books.filter(
    (book) =>
      book.title.toLowerCase().includes(q) ||
      book.author.toLowerCase().includes(q) ||
      book.tags.some((tag) => tag.toLowerCase().includes(q)) ||
      book.category.toLowerCase().includes(q)
  )
}
